### ISSUE TITLE
Not show on frontend

### ISSUE THREAD

**Issue by thanhnx991** [shopware/swag-docs-payment-plugin#6]
I'm installed plugin, it show payment on backend but not showing on frontend? 
It only showing default payment. I used shopware-platform-vagrant (https://github.com/shopwareLabs/shopware-platform-vagrant)

**Comment by rommelfreddy** [comment]
same issue. 
i have created a custom payment method. also the same issue.

**Comment by rommelfreddy** [comment]
upps ... not an issue
you should allow the payment method in the sales channel setting.
Then the payment method will appear in the storefront.

**Comment by maxwhite** [comment]
thank you @rommelfreddy you saved my time :)

**Comment by mitelg** [comment]
so, I think this could be closed? :blush: 

If not, please let me know
