### ISSUE TITLE
undefined method $this->getClassName()

### ISSUE THREAD

**Issue by WebKenth** [shopware/swag-docs-payment-plugin#8]
https://github.com/shopware/swag-docs-payment-plugin/blob/85502456496f53cb0929793564165a3583cf94c7/src/PaymentPlugin.php#L54

According to the [docs](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/payment-plugin) it's supposed to be 

`$pluginId = $pluginIdProvider->getPluginIdByBaseClass(get_class($this), $context);`

not

`$pluginId = $pluginIdProvider->getPluginIdByBaseClass($this->getClassName(), $context);`

**Comment by mitelg** [comment]
thanks for your report @WebKenth :+1:
